version: '3.8'

services:
  student-service:
    build: .
    container_name: student-service-container
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
    networks:
      - student-network

networks:
  student-network:
    driver: bridge
